"""Write src/beamer2slides/pdf/pure/psnames_data.py from FreeType's own glyph-name tables.

PDFium names glyphs through FreeType's psnames tables (src/psnames/pstables.h): its
UnicodeFromAdobeName walks `ft_adobe_glyph_list`, a trie of the legacy Adobe Glyph List plus the
ITC Zapf Dingbats names, one value per name, and a TrueType `post` table of format 1 or 2 names its
glyphs by `ft_mac_names`, the 258 standard Macintosh names. fontTools' LEGACY_AGL2UV comes close
(14 dingbat names short, and names with two values need a rule), so the pure reader carries the trie's
own answers: every name the trie knows with its value, and the Mac names in order.

    python tools/freetype_psnames_data.py [--from DIR]

fetches pstables.h at PIN (the FreeType PDFium's third_party/freetype pins at chromium/7999), or
reads it from DIR (flattened name, as src_psnames_pstables.h)."""
from __future__ import annotations

import argparse
import re
import urllib.request
from pathlib import Path

PIN = "656cb777"   # FreeType 2.14.3+, PDFium chromium/7999's third_party/freetype/src
FILE = "src/psnames/pstables.h"
OUT = Path(__file__).resolve().parents[1] / "src" / "beamer2slides" / "pdf" / "pure" / "psnames_data.py"


def fetch(local: Path | None) -> str:
    if local is not None:
        return (local / FILE.replace("/", "_")).read_text(encoding="utf-8")
    url = f"https://gitlab.freedesktop.org/freetype/freetype/-/raw/{PIN}/{FILE}"
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8")


def body(src: str, name: str) -> str:
    i = src.index(name)
    text = src[src.index("{", i) + 1:src.index("}", i)]
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def agl(src: str) -> dict[str, int]:
    """Every (name, value) of `ft_adobe_glyph_list`, walked the way ft_get_adobe_glyph_index reads
    it: a node is a letter (bit 7: one child follows inline), else a count byte (bit 7: a value
    follows) and the children's offsets."""
    t = [int(x, 0) for x in re.findall(r"\b(?:0x[0-9A-Fa-f]+|\d+)\b", body(src, "ft_adobe_glyph_list["))]
    out: dict[str, int] = {}

    def walk(off: int, prefix: str) -> None:
        while t[off] & 128:
            prefix += chr(t[off] & 127)
            off += 1
        prefix += chr(t[off] & 127)
        count, p = t[off + 1] & 127, off + 2
        if t[off + 1] & 128:
            out[prefix] = (t[off + 2] << 8) | t[off + 3]
            p += 2
        for i in range(count):
            walk((t[p + 2 * i] << 8) | t[p + 2 * i + 1], prefix)

    for i in range(t[1]):
        walk((t[2 + 2 * i] << 8) | t[3 + 2 * i], "")
    return out


def mac_names(src: str) -> list[str]:
    chars = re.findall(r"'(\\?.)'|\b(0)\b", body(src, "ft_standard_glyph_names["))
    blob = "".join("\0" if zero else c.replace("\\", "") for c, zero in chars)
    offsets = [int(x) for x in re.findall(r"\d+", body(src, "ft_mac_names["))]
    assert len(offsets) == 258
    return [blob[o:blob.index("\0", o)] for o in offsets]


def build(local: Path | None = None) -> str:
    src = fetch(local)
    names = agl(src)
    mac = mac_names(src)
    assert mac[0] == ".notdef" and mac[3] == "space", mac[:4]

    def lines(items: list[str], width: int = 96) -> str:
        out, line = [], ""
        for it in items:
            if len(line) + len(it) + 1 > width:
                out.append(line)
                line = ""
            line += it + " "
        out.append(line)
        return "\n".join(s.rstrip() for s in out)

    return f'''"""FreeType's glyph-name tables as PDFium reads them. Generated by tools/freetype_psnames_data.py
from FreeType {PIN} (src/psnames/pstables.h; FreeType License, (c) David Turner, Robert Wilhelm and
Werner Lemberg) - do not edit by hand.

- `AGL`: name -> value of every name `ft_get_adobe_glyph_index` finds ({len(names)} names).
- `MAC_NAMES`: `ft_mac_names`, the 258 standard Macintosh glyph names in order."""

_AGL = """
{lines([f"{n}:{v:04X}" for n, v in sorted(names.items())])}
"""

AGL = {{n: int(v, 16) for n, v in (s.split(":") for s in _AGL.split())}}

MAC_NAMES = tuple("""
{lines(mac)}
""".split())
'''


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--from", dest="local", type=Path, help="read pstables.h from this folder")
    args = ap.parse_args()
    OUT.write_text(build(args.local), encoding="utf-8", newline="\n")
    print("wrote", OUT, OUT.stat().st_size, "bytes")
