"""Write src/beamer2slides/pdf/pure/unicode_data.py from PDFium's own Unicode tables.

PDFium's text page does not use the Unicode data of the day: bidi classes and mirrors come from
core/fxcrt/fx_ucddata.inc (+ kFXTextLayoutBidiMirror in fx_unicode.cpp), and the decomposition a
right-to-left character is split into from core/fpdftext/unicodenormalizationdata.cpp. Both are an
old snapshot with Foxit's own choices (U+00A8 decomposes to U+0308 alone, U+0083 to "f", an
unassigned Hebrew code point is right to left), 3,982 bidi directions and 3,996 decompositions
apart from Python's `unicodedata`. So the pure reader carries PDFium's tables, cut down to what it
reads: the CFX_BidiChar direction per code unit (as runs), the mirror pairs, and every non-trivial
GetUnicodeNormalization answer.

    python tools/pdfium_unicode_data.py [--from DIR]

fetches the three files at PIN (the chromium/7999 branch pypdfium2's PDFium is built from; main
had the same data when this was written), or reads them from DIR (flattened names, as
core_fxcrt_fx_ucddata.inc)."""
from __future__ import annotations

import argparse
import base64
import re
import urllib.request
from pathlib import Path

PIN = "e9fc01804a0c5224ea780ad782abb8cfede628ef"   # refs/heads/chromium/7999
FILES = ["core/fxcrt/fx_ucddata.inc", "core/fxcrt/fx_unicode.cpp", "core/fpdftext/unicodenormalizationdata.cpp"]
OUT = Path(__file__).resolve().parents[1] / "src" / "beamer2slides" / "pdf" / "pure" / "unicode_data.py"

# CFX_BidiChar::AppendChar
LEFT, RIGHT, LEFT_WEAK = 1, 2, 3
DIRECTION = {"kL": LEFT, "kR": RIGHT, "kAL": RIGHT, **{k: LEFT_WEAK for k in
             ("kAN", "kEN", "kNSM", "kCS", "kES", "kET", "kBN")}}


def fetch(path: str, local: Path | None) -> str:
    if local is not None:
        return (local / path.replace("/", "_")).read_text(encoding="utf-8")
    url = f"https://pdfium.googlesource.com/pdfium/+/{PIN}/{path}?format=TEXT"
    with urllib.request.urlopen(url, timeout=60) as r:
        return base64.b64decode(r.read()).decode("utf-8")


def array(src: str, name: str) -> list[int]:
    i = src.index(name + " =") if name + " =" in src else src.index(name + "[] =")
    body = src[src.index("{", i) + 1:src.index("};", i)]
    return [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]+", body)]


def build(local: Path | None = None) -> str:
    rows = re.findall(r"CHARPROP____\((0x[0-9a-fA-F]+)u?, (\w+), (\w+), (\w+)\)",
                      fetch(FILES[0], local))
    assert len(rows) == 65536, len(rows)
    mirror_table = array(fetch(FILES[1], local), "kFXTextLayoutBidiMirror")
    norm_src = fetch(FILES[2], local)
    main = array(norm_src, "kUnicodeDataNormalization")
    maps = [array(norm_src, f"kUnicodeDataNormalizationMap{i}") for i in (1, 2, 3, 4)]
    assert len(main) == 65536

    direction = [DIRECTION.get(bd, 0) for _, _, bd, _ in rows]
    runs = [(u, d) for u, d in enumerate(direction) if u == 0 or d != direction[u - 1]]
    mirrors = {u: mirror_table[int(m, 16)] for u, (m, _, _, _) in enumerate(rows) if int(m, 16) != 0x1FF}

    def normalization(wch: int) -> list[int]:   # GetUnicodeNormalization
        f = main[wch]
        if not f:
            return [wch]
        if f >= 0x8000:
            return [maps[0][f - 0x8000]]
        wch, f = f & 0x0FFF, f >> 12
        m = maps[f - 1][wch:]
        if f == 4:
            f, m = m[0], m[1:]
        return m[:f]

    pieces = {u: normalization(u) for u in range(65536) if main[u]}

    def lines(items: list[str], width: int = 96) -> str:
        out, line = [], ""
        for it in items:
            if len(line) + len(it) + 1 > width:
                out.append(line)
                line = ""
            line += it + " "
        out.append(line)
        return "\n".join(s.rstrip() for s in out)

    return f'''"""PDFium's Unicode tables as its text page reads them. Generated by tools/pdfium_unicode_data.py
from PDFium {PIN[:12]} (chromium/7999; BSD-licensed data, (c) The PDFium Authors and Foxit) -
do not edit by hand.

- `direction(u)`: CFX_BidiChar's direction of a UTF-16 code unit (GetBidiClass: 0 neutral, 1 left,
  2 right, 3 left weak); past U+FFFF the table has no entry and the class is kON (neutral).
- `mirror(u)`: GetMirrorChar.
- `normalization(u)`: GetUnicodeNormalization (`wch & 0xFFFF`, the code unit itself when the
  table has nothing)."""

_DIRECTION_RUNS = """
{lines([f"{u:04X}:{d}" for u, d in runs])}
"""

_MIRRORS = """
{lines([f"{u:04X}:{v:04X}" for u, v in mirrors.items()])}
"""

_PIECES = """
{lines([f"{u:04X}:" + ",".join(f"{p:04X}" for p in ps) for u, ps in pieces.items()])}
"""


def _table() -> bytearray:
    out = bytearray(65536)
    runs = [(int(u, 16), int(d)) for u, d in (s.split(":") for s in _DIRECTION_RUNS.split())]
    for (start, d), (end, _) in zip(runs, runs[1:] + [(65536, 0)]):
        out[start:end] = bytes([d]) * (end - start)
    return out


_DIRECTION = _table()
MIRROR = {{int(a, 16): int(b, 16) for a, b in (s.split(":") for s in _MIRRORS.split())}}
PIECES = {{int(a, 16): tuple(int(p, 16) for p in b.split(","))
          for a, b in (s.split(":") for s in _PIECES.split())}}


def direction(u: int) -> int:
    return _DIRECTION[u] if u < 65536 else 0


def mirror(u: int) -> int:
    return MIRROR.get(u, u) if u < 65536 else u


def normalization(u: int) -> list[int]:
    u &= 0xFFFF
    return list(PIECES.get(u, (u,)))
'''


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--from", dest="local", type=Path, help="read the PDFium files from this folder")
    args = ap.parse_args()
    OUT.write_text(build(args.local), encoding="utf-8", newline="\n")
    print("wrote", OUT, OUT.stat().st_size, "bytes")
